### ISSUE TITLE
This is not an injector, it is a rewrite of the ZR API

### ISSUE THREAD

**Issue by Naqu6** [rselwyn/zr-code-injector#1]

**Comment by jimbo1qaz** [comment]
The name doesn't really make sense...?

**Comment by rselwyn** [comment]
@jimbo1qaz This project was originally just a zero code compiler.  It was named the "zr-code-injector" because of the way that it compiles the code.  Compilation works by "injecting" all of the zero robotics functions and objects, and then compiling the code.
